spring.application.name=backendlab

spring.datasource.url=jdbc:postgresql://${DB_ADDRESS}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.api-docs.path=/v3/api-docs

spring.mvc.problemdetails.enabled=true

jwt.private.key=5550cb73d75b73a9e621a501379ccc2241ffb28ae5138655d3d267a3de420e5d058f36435dbdf984f1c951e471a9638ca916525bdfa9811e09ba0c545ee7144a

mybatis.mapper-locations=classpath*:dao/*.xml